### ISSUE TITLE
Completion showing per account not character

### ISSUE THREAD

**Issue by Spennig** [Hubbotu/Radiant-Echoes-Timer#1]
I just downloaded this, because I liked the idea of being able to tell which characters had completed the Radiant quests so far, but it's showing the same data for all charactrers.

This is one of my alts that I haven't done ANY Radiant quests on yet: 
![image](https://github.com/user-attachments/assets/a4a9f3c7-53da-45bd-89a2-804b8b8be7d8)

Is there a way to set this to only show per character?

**Comment by Spennig** [comment]
Or blizzard went and made it account wide now... ::sigh::

**Comment by Hubbotu** [comment]
These quests are per account.

**Comment by Spennig** [comment]
> These quests are per account.

Yeah, I found that after I had posted. I missed that it was patched beyond being every hour, yesterday. Thanks
